import type { Metadata } from "next";

import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import { auth } from "@/server/auth";
import { fontMono, fontSans, fontSerif } from "@/lib/fonts";
import { ThemeProvider, SessionProvider } from "@/components/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(
            fontMono.variable,
            fontSans.variable,
            fontSerif.variable,
            "antialiased font-sans"
          )}
        >
          <ThemeProvider
            attribute="class"
            storageKey="theme"
            enableSystem
            defaultTheme="system"
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
